import type { Product } from "@/lib/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Royal Banarasi Silk Saree",
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    images: ["/elegant-banarasi-silk-saree-royal-blue-gold-zari.jpg", "/banarasi-saree-detail-gold-border.jpg", "/banarasi-saree-blouse-design.jpg"],
    category: "sarees",
    subcategory: "silk-sarees",
    description:
      "Exquisite handwoven Banarasi silk saree with intricate gold zari work. Perfect for weddings and special occasions.",
    fabric: "Pure Silk",
    care: ["Dry clean only", "Store in cotton cloth", "Avoid direct sunlight"],
    sizes: ["Free Size"],
    colors: ["Royal Blue", "Maroon", "Emerald Green"],
    inStock: true,
    stockCount: 15,
    rating: 4.8,
    reviewCount: 124,
    isNew: false,
    isFeatured: true,
    artisan: {
      name: "Masterji Ravi Kumar",
      location: "Varanasi, Uttar Pradesh",
      story: "Third generation weaver specializing in traditional Banarasi techniques passed down through family.",
      image: "/indian-artisan-weaver-portrait.jpg",
    },
    heritage: {
      region: "Varanasi",
      craft: "Banarasi Weaving",
      history: "Dating back to the Mughal era, Banarasi sarees are known for their gold and silver brocade work.",
    },
  },
  {
    id: "2",
    name: "Chanderi Cotton Kurta Set",
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    images: ["/placeholder-bxrbz.png", "/placeholder-xlnm0.png", "/placeholder-imqmb.png"],
    category: "kurta-sets",
    subcategory: "cotton-kurtas",
    description: "Elegant Chanderi cotton kurta set with delicate gold thread embroidery and matching dupatta.",
    fabric: "Chanderi Cotton",
    care: ["Hand wash in cold water", "Dry in shade", "Iron on medium heat"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Ivory White", "Powder Blue", "Mint Green"],
    inStock: true,
    stockCount: 32,
    rating: 4.6,
    reviewCount: 89,
    isNew: true,
    isFeatured: false,
    artisan: {
      name: "Sita Devi",
      location: "Chanderi, Madhya Pradesh",
      story: "Expert in traditional Chanderi weaving with over 20 years of experience.",
      image: "/placeholder-oqoz8.png",
    },
    heritage: {
      region: "Chanderi",
      craft: "Chanderi Weaving",
      history:
        "Chanderi fabric has been woven since the 13th century, known for its sheer texture and lightweight feel.",
    },
  },
  {
    id: "3",
    name: "Bandhani Lehenga Choli",
    price: 12999,
    images: ["/placeholder-5xi3u.png", "/placeholder-cws89.png", "/placeholder-ug17b.png"],
    category: "lehengas",
    subcategory: "traditional-lehengas",
    description: "Vibrant Bandhani lehenga choli with traditional tie-dye patterns and mirror work embellishments.",
    fabric: "Georgette with Cotton Lining",
    care: ["Dry clean recommended", "Store carefully to avoid mirror damage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Fuchsia Pink", "Royal Blue", "Orange Red"],
    inStock: true,
    stockCount: 8,
    rating: 4.7,
    reviewCount: 56,
    isNew: false,
    isFeatured: true,
    artisan: {
      name: "Kailash Chand",
      location: "Jaipur, Rajasthan",
      story: "Master craftsman in Bandhani tie-dye technique with expertise in mirror work embellishments.",
      image: "/placeholder-0exfb.png",
    },
    heritage: {
      region: "Rajasthan",
      craft: "Bandhani Tie-Dye",
      history:
        "Bandhani is an ancient tie-dye technique that creates beautiful dotted patterns, popular in Rajasthan and Gujarat.",
    },
  },
  {
    id: "4",
    name: "Kanjivaram Silk Saree",
    price: 22999,
    originalPrice: 28999,
    discount: 21,
    images: ["/placeholder-rabwy.png", "/placeholder-f5rwk.png", "/placeholder-wvxo5.png"],
    category: "sarees",
    subcategory: "silk-sarees",
    description: "Authentic Kanjivaram silk saree with temple border design and rich gold zari work.",
    fabric: "Pure Mulberry Silk",
    care: ["Professional dry clean only", "Store with muslin cloth", "Handle with care"],
    sizes: ["Free Size"],
    colors: ["Deep Purple", "Emerald Green", "Crimson Red"],
    inStock: true,
    stockCount: 6,
    rating: 4.9,
    reviewCount: 78,
    isNew: false,
    isFeatured: true,
    artisan: {
      name: "Murugan Swamy",
      location: "Kanchipuram, Tamil Nadu",
      story: "Fourth generation silk weaver maintaining traditional Kanjivaram techniques.",
      image: "/placeholder.svg?height=200&width=200",
    },
    heritage: {
      region: "Kanchipuram",
      craft: "Kanjivaram Silk Weaving",
      history: "Kanjivaram sarees originated in the 15th century and are considered the queen of all silk sarees.",
    },
  },
  {
    id: "5",
    name: "Phulkari Dupatta Set",
    price: 3999,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    category: "dupattas",
    subcategory: "embroidered-dupattas",
    description: "Traditional Phulkari dupatta with vibrant silk thread embroidery in floral patterns.",
    fabric: "Cotton with Silk Embroidery",
    care: ["Hand wash gently", "Dry flat in shade", "Iron on reverse side"],
    sizes: ["2.5m x 1m"],
    colors: ["Red Base", "Yellow Base", "Green Base"],
    inStock: true,
    stockCount: 25,
    rating: 4.5,
    reviewCount: 43,
    isNew: true,
    isFeatured: false,
    artisan: {
      name: "Gurpreet Kaur",
      location: "Patiala, Punjab",
      story: "Specialist in traditional Phulkari embroidery, learned from her grandmother.",
      image: "/placeholder.svg?height=200&width=200",
    },
    heritage: {
      region: "Punjab",
      craft: "Phulkari Embroidery",
      history:
        "Phulkari means flower work and is a traditional embroidery technique from Punjab dating back centuries.",
    },
  },
  {
    id: "6",
    name: "Ajrakh Block Print Kurta",
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    category: "kurtas",
    subcategory: "block-print-kurtas",
    description: "Handcrafted Ajrakh block print kurta with traditional geometric patterns in natural indigo dye.",
    fabric: "Cotton",
    care: ["Wash separately first time", "Use mild detergent", "Dry in shade"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Indigo Blue", "Madder Red", "Natural Black"],
    inStock: true,
    stockCount: 18,
    rating: 4.4,
    reviewCount: 67,
    isNew: false,
    isFeatured: false,
    artisan: {
      name: "Ibrahim Khatri",
      location: "Ajrakhpur, Gujarat",
      story: "Ninth generation Ajrakh printer preserving this ancient craft with natural dyes.",
      image: "/placeholder.svg?height=200&width=200",
    },
    heritage: {
      region: "Kutch, Gujarat",
      craft: "Ajrakh Block Printing",
      history:
        "Ajrakh is a 4000-year-old block printing technique using natural dyes and intricate geometric patterns.",
    },
  },
]

export const categories = [
  { id: "sarees", name: "Sarees", count: 156 },
  { id: "kurta-sets", name: "Kurta Sets", count: 89 },
  { id: "lehengas", name: "Lehengas", count: 67 },
  { id: "kurtas", name: "Kurtas", count: 134 },
  { id: "dupattas", name: "Dupattas", count: 78 },
  { id: "accessories", name: "Accessories", count: 45 },
]

export const colors = ["Red", "Blue", "Green", "Yellow", "Pink", "Purple", "Orange", "Black", "White", "Gold"]

export const sizes = ["XS", "S", "M", "L", "XL", "XXL", "Free Size"]

export const fabrics = ["Cotton", "Silk", "Georgette", "Chiffon", "Crepe", "Linen", "Chanderi", "Banarasi"]
